from pathlib import Path
from scraper.api.app import create_app


def test_openapi_schema_matches_routes():
    """Verify that OpenAPI schema generated by FastAPI contains all expected routes and models (§DS-26)."""
    app = create_app()
    openapi_schema = app.openapi()

    assert openapi_schema is not None
    assert "paths" in openapi_schema
    paths = openapi_schema["paths"]

    # Verify all primary API endpoints are documented
    assert "/api/v1/health" in paths
    assert "/api/v1/capabilities" in paths
    assert "/api/v1/inspect" in paths
    assert "/api/v1/crawl" in paths
    assert "/api/v1/crawl/{job_id}" in paths
    assert "/api/v1/research" in paths
    assert "/api/v1/research/{run_id}" in paths
    assert "/api/v1/metrics/summary" in paths


def test_release_documentation_integrity():
    """Verify that canonical documentation, changelog, and openapi.yaml exist and have valid structure (§DS-26)."""
    root_dir = Path(__file__).resolve().parent.parent

    changelog_path = root_dir / "CHANGELOG.md"
    assert changelog_path.exists(), "CHANGELOG.md must exist"
    changelog_content = changelog_path.read_text(encoding="utf-8")
    assert "[1.0.0-rc1]" in changelog_content
    assert "Capability Matrix" in changelog_content

    openapi_path = root_dir / "docs" / "openapi.yaml"
    assert openapi_path.exists(), "docs/openapi.yaml must exist"
    openapi_content = openapi_path.read_text(encoding="utf-8")
    assert "openapi: 3.0.3" in openapi_content
    assert "/inspect" in openapi_content
    assert "/crawl" in openapi_content
    assert "/research" in openapi_content

    audit_path = root_dir / "docs" / "architecture" / "AUDIT_REPORT.md"
    assert audit_path.exists(), "docs/architecture/AUDIT_REPORT.md must exist"
    audit_content = audit_path.read_text(encoding="utf-8")
    assert "1.0.0-rc1" in audit_content
