"""Source Type Taxonomy (DS-SI47)."""

from enum import Enum


class SourceType(str, Enum):
    OFFICIAL_DOC = "OFFICIAL_DOC"
    PRIMARY_RESEARCH = "PRIMARY_RESEARCH"
    SYSTEMATIC_REVIEW = "SYSTEMATIC_REVIEW"
    META_ANALYSIS = "META_ANALYSIS"
    GUIDELINE = "GUIDELINE"
    REGULATOR = "REGULATOR"
    NEWS_WIRE = "NEWS_WIRE"
    NEWS_MEDIA = "NEWS_MEDIA"
    GOVERNMENT = "GOVERNMENT"
    STANDARD = "STANDARD"
    SOURCE_CODE = "SOURCE_CODE"
    ISSUE_TRACKER = "ISSUE_TRACKER"
    FORUM = "FORUM"
    BLOG = "BLOG"
    WIKI = "WIKI"
    AGGREGATOR = "AGGREGATOR"
    MARKETING = "MARKETING"
    UNKNOWN = "UNKNOWN"
