package plan

import (
	"time"

	"github.com/Homiakus/axiom/adgo"
)

// ResearchPlanDefinition returns the canonical immutable research workflow graph (§2, §4, DS-A05).
func ResearchPlanDefinition() adgo.Definition {
	return adgo.Definition{
		ID:          "deepsearch-research-v1",
		Version:     "1.0.0",
		InitialData: []string{"query"},
		AllowedPermissions: []string{
			"network.read",
			"storage.write",
			"vector.write",
		},
		GlobalConcurrency: 16,
		CapabilityLimits: map[string]int{
			"web-search": 5,
			"crawler":    10,
			"embedding":  4,
		},
		Nodes: []adgo.Node{
			{
				ID:             "NormalizeQuery",
				Kind:           adgo.NodeActivity,
				Activity:       "NormalizeQuery",
				Capability:     "query-analyzer",
				Requires:       []string{"query"},
				Produces:       []string{"normalized_query"},
				Risk:           adgo.RiskLow,
				Timeout:        5 * time.Second,
				Retry:          adgo.RetryPolicy{MaxAttempts: 2, BaseDelay: 100 * time.Millisecond},
				IdempotencyKey: "NormalizeQuery",
				Next: []adgo.Transition{
					{To: "PlanResearch", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:             "PlanResearch",
				Kind:           adgo.NodeActivity,
				Activity:       "PlanResearch",
				Capability:     "research-planner",
				DependsOn:      []string{"NormalizeQuery"},
				Requires:       []string{"normalized_query"},
				Produces:       []string{"research_plan"},
				Risk:           adgo.RiskLow,
				Timeout:        10 * time.Second,
				Retry:          adgo.RetryPolicy{MaxAttempts: 3, BaseDelay: 500 * time.Millisecond},
				IdempotencyKey: "PlanResearch",
				Next: []adgo.Transition{
					{To: "DiscoverSources", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:                  "DiscoverSources",
				Kind:                adgo.NodeActivity,
				Activity:            "DiscoverSources",
				Capability:          "web-search",
				DependsOn:           []string{"PlanResearch"},
				Requires:            []string{"research_plan"},
				Produces:            []string{"discovered_seeds"},
				RequiredPermissions: []string{"network.read"},
				ExternalEffect:      true,
				Irreversible:        true,
				Risk:                adgo.RiskMedium,
				Timeout:             30 * time.Second,
				Retry:               adgo.RetryPolicy{MaxAttempts: 3, BaseDelay: time.Second, MaxDelay: 10 * time.Second},
				IdempotencyKey:      "DiscoverSources",
				Next: []adgo.Transition{
					{To: "RankSeeds", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:             "RankSeeds",
				Kind:           adgo.NodeActivity,
				Activity:       "RankSeeds",
				Capability:     "seed-ranker",
				DependsOn:      []string{"DiscoverSources"},
				Requires:       []string{"discovered_seeds"},
				Produces:       []string{"ranked_seeds"},
				Risk:           adgo.RiskLow,
				Timeout:        10 * time.Second,
				Retry:          adgo.RetryPolicy{MaxAttempts: 2, BaseDelay: 200 * time.Millisecond},
				IdempotencyKey: "RankSeeds",
				Next: []adgo.Transition{
					{To: "AcquireBatch", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:                  "AcquireBatch",
				Kind:                adgo.NodeActivity,
				Activity:            "AcquireBatch",
				Capability:          "crawler",
				DependsOn:           []string{"RankSeeds"},
				Requires:            []string{"ranked_seeds"},
				Produces:            []string{"acquired_artifacts"},
				RequiredPermissions: []string{"network.read"},
				ExternalEffect:      true,
				Irreversible:        true,
				Risk:                adgo.RiskMedium,
				Timeout:             120 * time.Second,
				Retry:               adgo.RetryPolicy{MaxAttempts: 3, BaseDelay: 2 * time.Second, MaxDelay: 30 * time.Second},
				IdempotencyKey:      "AcquireBatch",
				Next: []adgo.Transition{
					{To: "ExtractBatch", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:             "ExtractBatch",
				Kind:           adgo.NodeActivity,
				Activity:       "ExtractBatch",
				Capability:     "extractor",
				DependsOn:      []string{"AcquireBatch"},
				Requires:       []string{"acquired_artifacts"},
				Produces:       []string{"extracted_docs"},
				Risk:           adgo.RiskLow,
				Timeout:        60 * time.Second,
				Retry:          adgo.RetryPolicy{MaxAttempts: 2, BaseDelay: time.Second},
				IdempotencyKey: "ExtractBatch",
				Next: []adgo.Transition{
					{To: "NormalizeBatch", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:             "NormalizeBatch",
				Kind:           adgo.NodeActivity,
				Activity:       "NormalizeBatch",
				Capability:     "normalizer",
				DependsOn:      []string{"ExtractBatch"},
				Requires:       []string{"extracted_docs"},
				Produces:       []string{"normalized_docs"},
				Risk:           adgo.RiskLow,
				Timeout:        30 * time.Second,
				Retry:          adgo.RetryPolicy{MaxAttempts: 2, BaseDelay: 500 * time.Millisecond},
				IdempotencyKey: "NormalizeBatch",
				Next: []adgo.Transition{
					{To: "IndexBatch", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:                  "IndexBatch",
				Kind:                adgo.NodeActivity,
				Activity:            "IndexBatch",
				Capability:          "embedding",
				DependsOn:           []string{"NormalizeBatch"},
				Requires:            []string{"normalized_docs"},
				Produces:            []string{"indexed_chunks"},
				RequiredPermissions: []string{"vector.write"},
				ExternalEffect:      true,
				Irreversible:        true,
				Risk:                adgo.RiskMedium,
				Timeout:             60 * time.Second,
				Retry:               adgo.RetryPolicy{MaxAttempts: 3, BaseDelay: time.Second},
				IdempotencyKey:      "IndexBatch",
				Next: []adgo.Transition{
					{To: "BuildEvidence", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:             "BuildEvidence",
				Kind:           adgo.NodeActivity,
				Activity:       "BuildEvidence",
				Capability:     "evidence-builder",
				DependsOn:      []string{"IndexBatch"},
				Requires:       []string{"indexed_chunks"},
				Produces:       []string{"evidence_graph"},
				Risk:           adgo.RiskLow,
				Timeout:        45 * time.Second,
				Retry:          adgo.RetryPolicy{MaxAttempts: 2, BaseDelay: time.Second},
				IdempotencyKey: "BuildEvidence",
				Next: []adgo.Transition{
					{To: "EvaluateCoverage", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:             "EvaluateCoverage",
				Kind:           adgo.NodeActivity,
				Activity:       "EvaluateCoverage",
				Capability:     "coverage-evaluator",
				DependsOn:      []string{"BuildEvidence"},
				Requires:       []string{"evidence_graph"},
				Produces:       []string{"coverage_evaluation"},
				Risk:           adgo.RiskLow,
				Timeout:        20 * time.Second,
				Retry:          adgo.RetryPolicy{MaxAttempts: 2, BaseDelay: 500 * time.Millisecond},
				IdempotencyKey: "EvaluateCoverage",
				Next: []adgo.Transition{
					{To: "BuildArchive", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:                  "BuildArchive",
				Kind:                adgo.NodeActivity,
				Activity:            "BuildArchive",
				Capability:          "archive-exporter",
				DependsOn:           []string{"EvaluateCoverage"},
				Requires:            []string{"coverage_evaluation"},
				Produces:            []string{"research_archive"},
				RequiredPermissions: []string{"storage.write"},
				ExternalEffect:      true,
				Irreversible:        true,
				Risk:                adgo.RiskLow,
				Timeout:             30 * time.Second,
				Retry:               adgo.RetryPolicy{MaxAttempts: 3, BaseDelay: time.Second},
				IdempotencyKey:      "BuildArchive",
				Next: []adgo.Transition{
					{To: "CompleteResearch", Outcome: adgo.OutcomeCompleted},
				},
			},
			{
				ID:             "CompleteResearch",
				Kind:           adgo.NodeActivity,
				Activity:       "CompleteResearch",
				Capability:     "finalizer",
				DependsOn:      []string{"BuildArchive"},
				Requires:       []string{"research_archive"},
				Produces:       []string{"research_outcome"},
				Risk:           adgo.RiskLow,
				Timeout:        10 * time.Second,
				Retry:          adgo.RetryPolicy{MaxAttempts: 2, BaseDelay: 200 * time.Millisecond},
				IdempotencyKey: "CompleteResearch",
			},
		},
	}
}

// CompileResearchPlan compiles and validates the ResearchPlan definition.
func CompileResearchPlan() (*adgo.Plan, error) {
	return adgo.Compile(ResearchPlanDefinition())
}
